# Generated by Django 4.0.3 on 2022-03-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typer', '0002_alter_exercice_lesson_alter_exercice_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='seconds',
            field=models.IntegerField(default=0),
        ),
    ]
