# Generated by Django 4.0.3 on 2022-03-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typer', '0004_alter_course_pub_date_alter_exercice_pub_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
