# Generated by Django 4.0.3 on 2022-03-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typer', '0005_user_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
