# Generated by Django 4.0.3 on 2022-03-05 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typer', '0006_alter_user_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='language',
        ),
    ]
