# Generated by Django 4.0.3 on 2022-03-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typer', '0008_remove_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
