# Generated by Django 4.0.3 on 2022-03-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typer', '0009_user_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(default='B', max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='level_code',
            field=models.CharField(default='B', max_length=200),
        ),
    ]
