# Generated by Django 4.0.3 on 2022-04-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typer', '0012_lesson_next_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='locale',
            field=models.CharField(default='en', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='locale',
            field=models.CharField(default='en', max_length=20),
        ),
    ]
