# Generated by Django 4.0.3 on 2022-05-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typer', '0013_course_locale_user_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='order_n',
            field=models.IntegerField(default=1),
        ),
    ]
