# Generated by Django 4.0.3 on 2022-05-27 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('typer', '0014_lesson_order_n'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='next_lesson',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='typer.lesson'),
        ),
    ]
